name: Customer Service Contract Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [pact-changed]

jobs:
  provider-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run unit tests
      run: npm test
      env:
        PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
        PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
        GIT_COMMIT: ${{ github.sha }}
        
    - name: Run Pact provider verification tests
      run: npm run test:provider
      env:
        PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
        PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
        GIT_COMMIT: ${{ github.sha }}
        
    - name: Install Pact CLI globally
      run: npm install -g @pact-foundation/pact-cli
      
    - name: Can I Deploy? (Check if safe to deploy)
      run: |
        pact-broker can-i-deploy \
          --pacticipant CustomerService \
          --version ${{ github.sha }} \
          --broker-base-url ${{ secrets.PACT_BROKER_BASE_URL }} \
          --broker-token ${{ secrets.PACT_BROKER_TOKEN }}
      if: github.ref == 'refs/heads/main'